### ISSUE TITLE
mepo issue with moving fixtures

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#106]
This was discovered by @rtodling. To wit:

1. Clone repo to `/path/to/GEOSgcm`
2. Move repo to `/path/to/GEOSgcm-OLD`
3. Clone new repo to `/path/to/GEOSgcm`

The issue is that `mepo init` uses absolute paths during its setup. So if you move things like this, even the `GEOSgcm-OLD` clone will point to the *new* clone because one exists at that part of the tree.

**Comment by rtodling** [comment]
Just to add that this "renaming" of directories has been common practice among most, if not all, users of the DAS. I will have to ask that we come up w/ a fix for this before releasing the DAS to anyone beyond the small group of individuals presently testing the Git vs CVS migration.

**Comment by mathomp4** [comment]
I think #107 has a fix for this. I'm doing some more testing to be sure.
