### ISSUE TITLE
mepo aliases a la git aliases

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#139]
Per @JulesKouatchou:

> I know that in Git, you can issue the commands:
>  ```
> git config --global alias.co "checkout"
> git config --global alias.ci "commit"
> git config --global alias.cm "commit -m"
> git config --global alias.cam "commit -am"
> git config --global alias.st "status
>  ```
> and the following will be added to the .gitconfig file in your home directory:
>  ```
> [alias]
>         co = checkout
>         ci = commit
>         st = status
>         cm = commit -m
>         cam = commit -am
> ```
> I believe that it can be possible to do something similar with mepo:
> ``` 
> mepo config --global alias.co "checkout"
> memo config --global alias.ci "commit"
> mepo config --global alias.cm "commit -m"
> mepo config --global alias.cam "commit -am"
> mepo config --global alias.st "status
> ```
> and the a .mepoconfig YAML file will be created (if not already) with:
> ```yaml
>                         ---
> alias:
>         co: checkout
>         ci: commit
>         st: status
>         cm: commit -m
>         cam: commit -am
> ```
> If you want, I can explore and implement how it can be done.

**Comment by amdasilva** [comment]
Better to keep this on a specific $HOME/.mepoconfig. This way we can have other repo specific preferences, such as @ style saved as well.
