### ISSUE TITLE
Use relative-like paths in components.yaml?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#25]
This might be a "don't do" but I thought I'd raise it. Currently, `components.yaml` is hard-coded to use the git ssh style URLs. However, there is no real reason it couldn't support https as well.

I'm wondering if it would be possible to do something a la the git submodule route where "relative URLs" can sort of make the protocol not as important.

**Comment by tclune** [comment]
If the repo-specific portion is the same whether it is https or ssh, then this should be easy.    It is also related to my desire to have a global "host" portion of the URL and then only need to specify relative paths for the individual repos.
