### ISSUE TITLE
Construct "full" remote path - ssh

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/mepo#277]
`src/mepo/git.py` uses `urllib.parse.urljoin` to construct "full" remote url, but this does not work with url's with `ssh`. This needs a relook.

**Comment by mathomp4** [comment]
@pchakraborty Hmm. I mean, it has to work in current mepo as I use SSH urls all the time...unless I'm avoiding this somehow?

**Comment by pchakraborty** [comment]
@mathomp4 You are right. `urllib.parse.urljoin` seems to be working fine with `ssh` url's. Closing this.
