### ISSUE TITLE
State file: pickle to json

### ISSUE THREAD

**Issue by pchakraborty** [GEOS-ESM/mepo#284]
Consider switching to `json` serialization format for storing the state from the current `pickle` format. This would ensure that issues like #279 don't come up again. A `json.dump` without indentation should reduce the risk of hand editing of the state file. 

For an older clone, made with `mepo 1`, a warning will be displayed, along with a solution of how to update to `mepo 2` style state
> Converting mepo1 state to mepo2 state
Run `mepo update-state` to permanently convert to mepo2 state

**Comment by mathomp4** [comment]
Plus we'd be able to read the state file! 

That said, could we somehow "write-protect" the file? That is, only "easily" allow changes via mepo? I'd be afraid someone would see a json file and think, oh, I can just edit this.

I mean, it's not hard to `chmod +w` but at if the script would be able to toggle the write bits, that might make things a bit safer

**Comment by pchakraborty** [comment]
@mathomp4 That, I think, can be easily done.

We can also consider taking the string generated by `json.dumps` and convert it to binary via [ord](https://docs.python.org/3.8/library/functions.html#ord) or [bytearray](https://docs.python.org/3/library/functions.html#func-bytearray) save that to file. I'll look into this.

**Comment by pchakraborty** [comment]
The state file is now in json format and is read-only.
