### ISSUE TITLE
mepo tab completion is broken in mepo 2

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#304]
It looks like mepo tab-completion is broken in mepo 2. The current script seems to assume the `command` directory will be next to the `mepo` script-command:
```bash
    if [[ "$OSTYPE" == "darwin"* ]]
    then
       local mepodir=$(dirname $(readlink $(which mepo)))
    else
       local mepodir=$(dirname $(readlink -f $(which mepo)))
    fi
    for mydir in $(ls -d ${mepodir}/mepo.d/command/*/); do
        if [[ $mydir != *"__pycache__"* ]]; then
            mepo_cmd_list+=" $(basename $mydir)"
        fi
```

Now when someone, say, installs with Brew or pip, that command directory might be in a weird far-off directory.

**Comment by pchakraborty** [comment]
`mepo` completion works now. Will need to figure out a way to include the `etc` directory in the wheel package.
