### ISSUE TITLE
Add ability to checkout branch on all repos if it exists

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/mepo#33]
To help aid CircleCI (at least) it would be nice to be able to do:
```
mepo checkout --if-exists feature-branch-on-multiple-repos
```
where `mepo` would loop over every sub-repository and if that branch exists, check it out.

**Comment by mathomp4** [comment]
Or maybe:
```
mepo checkout-if-exists feature-branch-on-multiple-repos
```
since git itself doesn't really support this? Thoughts @tclune ?

**Comment by tclune** [comment]
Seems like this will be useful as well for Arlindo's use case.     Might quibble over the name of the option, but can't come up with anything better.

**Comment by mathomp4** [comment]
Well, I think I have `mepo checkout-if-exists` working. The `mepo checkout --if-exists` is a lot harder because by default it *requires* a component name. And I'm not sure how to handle an "if this option is passed, require no arguments, require one or more" very well.
